### ISSUE TITLE
fill depth for kitti dataset

### ISSUE THREAD

**Issue by PouyaNF** [JunjH/Visualizing-CNNs-for-monocular-depth-estimation#13]
in your paper, you mentioned using the NYU-v2 dataset to interpolate pixels with missing depth.
if you do that while training, it gets massive amounts of time!
please guide me on how to solve this? did you fill the depth before training?

**Comment by JunjH** [comment]
Yes, we filled the depth before training.

**Comment by PouyaNF** [comment]
would you please share the code for filling the sparse depth of Kitti? I used the NYU depth_colorization but the filled depth can be better I think. Did you use default parameters?  how can we get the high-quality (16-bit) depth map? 
this is the code I used for colorization :  [https://gist.github.com/ialhashim/be6235489a9c43c6d240e8331836586a#file-fill_depth_colorization-py](url)

and I used it this way :
rgb = Image.open(rgb_path).convert('RGB')
depth_png = np.array(Image.open(depth_path), dtype=int)
depth = depth_png.astype(np.float32) / 256.
depth = depth_png.astype(np.float32)
data = {'img': rgb, 'depth': depth}
image_data = rgb.convert('L')
image_gray_arr = np.array(image_data)
data['depth_interp'] = fill_depth_colorization(image_gray_arr, depth)
data['depth_interp'] = (data['depth_interp']).astype(np.float32)

**Comment by PouyaNF** [comment]
if I comment `depth = depth_png.astype(np.float32) / 256` does it make any improvement of the result?

**Comment by PouyaNF** [comment]
Dear Junjie,
please if it is possible for you, share your work on the Kitti dataset as
well. especially the way you complete sparse depth and save it. my results
on Kitti dataset are not interpretable and it generates an inappropriate
mask.

best wishes
