### ISSUE TITLE
depth map to Pseudo-color image 

### ISSUE THREAD

**Issue by ITking666** [JunjH/Visualizing-CNNs-for-monocular-depth-estimation#5]
hello Junj Hu
Can you share your code which can be used for converting depth map to Pseudo-color image .
I want to compare my depth estimation results with yours 
My email is 1474690467@.com

**Comment by abdulkampli** [comment]
Hello Junj Hu,
Could you please share your code that converts from depth map to heatmap.
my email ID is abdulrehaman.kampli4@gmail.com
Many Thanks
