### ISSUE TITLE
Miss match in pretrained models architecture and given base model architecture 

### ISSUE THREAD

**Issue by abdulkampli** [JunjH/Visualizing-CNNs-for-monocular-depth-estimation#9]
Hi JunjH,

while testing the Kitti dataset I am getting this error : 
Traceback (most recent call last):
  File "/content/visualize_kitti/test.py", line 123, in <module>
    main()
  File "/content/visualize_kitti/test.py", line 76, in main
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.E.base.0.conv1.weight", "module.E.base.0.bn1.weight", "module.E.base.0.bn1.bias", 

could you please share the correct base model architecture for eg. resnet.py

Mnay Thanks,
Abdul
<img width="436" alt="Capture" src="https://user-images.githubusercontent.com/81448071/114310618-9c95ff00-9aeb-11eb-9727-3d9c1ed8169f.PNG">

**Comment by PouyaNF** [comment]
Miss match in pretrained models architecture and given base model architecture
